### PR TITLE
updated xclim version

### LINKED ISSUE #50: Update xclim to latest version

### PR DESCRIPTION
**Pull request by huard**
## Overview

This PR fixes #50

### CODE REVIEW

**Comment by huard** [comment]
Broken due to https://github.com/Ouranosinc/xclim/issues/300

**Comment by huard** [comment]
@Zeitsperre Any idea why there would be a core dump ? All tests seem to pass.

**Comment by Zeitsperre** [comment]
That's really strange. I'm pushing a new build of conda with the fix to the recipe.yaml now. Maybe we can try re-running the Travis CI builds when that's done?

**Comment by tlvu** [comment]
Would like to release a new Finch docker image, can this PR be merged?

**Comment by huard** [comment]
I'll merge since the core dump issue is probably from upstream.

**Pull request merged**
