### PR TITLE
finch-usage.ipynb: update output due to new birdy 0.8.0

### PR DESCRIPTION
**Pull request by tlvu**
New birdy removed `output_formats`.

Clarification from DavidH: To clarify, the `output_formats` option still exists, but it's only appearing when the process has a complexoutput supporting more than one data format. 
https://github.com/bird-house/birdy/commit/2bea46c1aa20a91dfe38741476e202919c4b1ffa#diff-ba0f245ac7a3747697d42961f7a19568e294dc5d2b4ad14b62a47d8c240ed12eR230-R238

Also removed `NBVAL_IGNORE_OUTPUT` since Jenkins is configured to by
default ignore html changes, see PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/73.

Jenkins passing build with upcoming Jupyter env: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-docker-build-for-ravenpy/10/console

New Jupyter env PR: https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/75

To fix this error:
```
  _________ finch-master/docs/source/notebooks/finch-usage.ipynb::Cell 1 _________
  Notebook cell execution failed
  Cell 1: Cell outputs differ

  Input:
  help(wps.frost_days)

  Traceback:
   mismatch 'stdout'

   assert reference_output == test_output failed:

    'Help on meth...ut files.\n\n' == 'Help on meth...ut files.\n\n'
    Skipping 201 identical leading characters in diff, use -v to show
    - iable=None) method of birdy.client.base.WPSClient instance
    + iable=None, output_formats=None) method of birdy.client.base.WPSClient instance
    ?           +++++++++++++++++++++
          Number of days where daily minimum temperatures are below 0.

          Parameters
          ----------
          tasmin : ComplexData:mimetype:`application/x-netcdf`, :mimetype:`application/x-ogc-dods`
              NetCDF Files or archive (tar/zip) containing netCDF files.
          thresh : string
              Freezing temperature.
          freq : {'YS', 'MS', 'QS-DEC', 'AS-JUL'}string
              Resampling frequency.
          check_missing : {'any', 'wmo', 'pct', 'at_least_n', 'skip', 'from_context'}string
              Method used to determine which aggregations should be considered missing.
          missing_options : ComplexData:mimetype:`application/json`
              JSON representation of dictionary of missing method parameters.
          cf_compliance : {'log', 'warn', 'raise'}string
              Whether to log, warn or raise when inputs have non-CF-compliant attributes.
          data_validation : {'log', 'warn', 'raise'}string
              Whether to log, warn or raise when inputs fail data validation checks.
          variable : string
              Name of the variable in the NetCDF file.

          Returns
          -------
          output_netcdf : ComplexData:mimetype:`application/x-netcdf`
              The indicator values computed on the original input grid.
          output_log : ComplexData:mimetype:`text/plain`
              Collected logs during process run.
          ref : ComplexData:mimetype:`application/metalink+xml; version=4.0`
              Metalink file storing all references to output files.
```

## Overview

This PR fixes [issue id]

Changes:

* Added ...

## Additional Information

Links to other issues or sources.

### CODE REVIEW

**Review by huard — APPROVED** [review]
To clarify, the `output_formats` option still exists, but it's only appearing when the process has a complexoutput supporting more than one data format.

**Comment by tlvu** [comment]
> To clarify, the `output_formats` option still exists, but it's only appearing when the process has a complexoutput supporting more than one data format.
> [bird-house/birdy@2bea46c#diff-ba0f245ac7a3747697d42961f7a19568e294dc5d2b4ad14b62a47d8c240ed12eR230-R238](https://github.com/bird-house/birdy/commit/2bea46c1aa20a91dfe38741476e202919c4b1ffa#diff-ba0f245ac7a3747697d42961f7a19568e294dc5d2b4ad14b62a47d8c240ed12eR230-R238)

Oh ok thanks for clarification !

**Comment by tlvu** [comment]
Merge anyways since test failure not related to the notebook I updated:
```
________________________ test_ensemble_dded_grid_point _________________________
Traceback (most recent call last):
  File "/home/runner/work/finch/finch/tests/utils.py", line 76, in execute_process
    assert_response_success(response)
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/pywps/tests.py", line 148, in assert_response_success
    assert len(success) == 1
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/finch/finch/tests/test_wps_ensemble.py", line 90, in test_ensemble_dded_grid_point
    outputs = execute_process(client, identifier, inputs, output_names=["output"])
  File "/home/runner/work/finch/finch/tests/utils.py", line 82, in execute_process
    raise ProcessError(output_message) from e
pywps.app.exceptions.ProcessError: NoApplicableCode: Process error: Finch failed with AttributeError dict object has no attribute collection_annotations
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/home/runner/work/finch/finch/finch/processes/wps_base.py", line 39, in _handler_wrapper
    return self.wrapped_handler(request, response)
  File "/home/runner/work/finch/finch/finch/processes/wps_ensemble_indices_point.py", line 77, in _handler
    return ensemble_common_handler(self, request, response, finch_subset_gridpoint)
  File "/home/runner/work/finch/finch/finch/processes/ensemble_utils.py", line 579, in ensemble_common_handler
    output_ds = compute_indices(process, process.xci, inputs)
  File "/home/runner/work/finch/finch/finch/processes/utils.py", line 181, in compute_indices
    out = func(**kwds)
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/xclim/core/indicator.py", line 655, in __call__
    outs = self.compute(**das, **ba.kwargs)
  File "<boltons.funcutils.FunctionBuilder-97>", line 2, in degree_days_exceedance_date
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/xclim/core/units.py", line 600, in wrapper
    out = func(*args, **kwargs)
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/xclim/indices/_threshold.py", line 1723, in degree_days_exceedance_date
    out = c.clip(0).resample(time=freq).map(_exceedance_date)
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/xarray/core/resample.py", line 222, in map
    combined = super().map(func, shortcut=shortcut, args=args, **kwargs)
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/xarray/core/groupby.py", line 799, in map
    return self._combine(applied, shortcut=shortcut)
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/xarray/core/groupby.py", line 818, in _combine
    applied_example, applied = peek_at(applied)
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/xarray/core/utils.py", line 194, in peek_at
    peek = next(gen)
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/xarray/core/groupby.py", line 798, in <genexpr>
    applied = (maybe_wrap_array(arr, func(arr, *args, **kwargs)) for arr in grouped)
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/xclim/indices/_threshold.py", line 1717, in _exceedance_date
    return rl.first_run_after_date(
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/xclim/indices/run_length.py", line 692, in first_run_after_date
    return first_run(
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/xclim/indices/run_length.py", line 305, in first_run
    out = lazy_indexing(crd, out)
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/xclim/indices/run_length.py", line 1017, in lazy_indexing
    out = index.map_blocks(func)
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/xarray/core/dataarray.py", line 3704, in map_blocks
    return map_blocks(func, self, args, kwargs, template)
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/xarray/core/parallel.py", line 563, in map_blocks
    data = dask.array.Array(
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/dask/array/core.py", line 1159, in __new__
    if layer.collection_annotations is None:
AttributeError: 'dict' object has no attribute 'collection_annotations'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/finch-wps/lib/python3.9/site-packages/pywps/app/Process.py", line 248, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/home/runner/work/finch/finch/finch/processes/wps_base.py", line 42, in _handler_wrapper
    raise ProcessError(f"Finch failed with {err!r}")
pywps.app.exceptions.ProcessError: Finch failed with AttributeError dict object has no attribute collection_annotations
```

**Comment by aulemahal** [comment]
That error comes from a mismatch between xarray and dask, It is supposed to be fixed with xr 0.18.2 and dask >= 2021.05, what versions are being used here?

**Comment by tlvu** [comment]
> That error comes from a mismatch between xarray and dask, It is supposed to be fixed with xr 0.18.2 and dask >= 2021.05, what versions are being used here?

From https://github.com/bird-house/finch/runs/2686596921 it looks like `xarray-0.17.0` and `dask-2021.5.0`.

**Comment by aulemahal** [comment]
Ok! If I recall correctly, this breaking change was unnannounced by dask, which is why 2021.5.0 makes any xarray < 0.18.1 break. (But xr 0.18.1 is also broken in itself :roll_eyes: ).

**Pull request merged**
