### PR TITLE
Refresh cookiecutter for more robust doc build

### PR DESCRIPTION
**Pull request by tlvu**
## Overview

This PR applies the cookiecutter PR https://github.com/bird-house/cookiecutter-birdhouse/pull/96 to ensure no silent ReadTheDocs build failure and for Travis-CI to also catch ReadTheDocs build failure before PR is merged.

Successful RtD generation: https://pavics-sdi.readthedocs.io/projects/finch/en/test-rtd-build/ and matching RtD build logs: https://readthedocs.org/api/v2/build/11555597.txt (commit f5c857e3a453413029c2f23343832e949c479145) 

Changes:

* Turn RtD warnings to build failure so they do not fail silently.

* Change Travis-CI build config to also build Epub and Latex doc format to catch RtD failure on Travis-CI before PR is merged.

* Various changes to remove all warnings in doc build since warnings will now fail the doc build.

* setup.py: fix `make develop` not installing `requirements_dev.txt` as expected

* add notebooks `finch-usage.ipynb` and `dap_subset.ipynb` to RtD

Unrelated changes part of this PR (sorry !):

* Other cookiecutter changes that are unapplied previously are also part of this PR.  You might want to look at each commit to avoid the noises.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
Nice.

**Comment by tlvu** [comment]
> Nice.

Nice for getting completely unrelated error to my changes? :(

```
$ make test-notebooks
Copying notebook output sanitizer ...
Running notebook-based tests
[1m============================= test session starts ==============================[0m
platform linux -- Python 3.7.8, pytest-6.0.0, py-1.9.0, pluggy-0.13.1 -- /home/travis/miniconda/envs/finch/bin/python
cachedir: .pytest_cache
rootdir: /home/travis/build/bird-house/finch, configfile: setup.cfg
plugins: nbval-0.9.5, notebook-0.6.0, flake8-1.0.6
[1mcollecting ... [0m[1m
collected 0 items / 1 error                                                    [0m

==================================== ERRORS ====================================
[31m[1m________________________ ERROR collecting test session _________________________[0m
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/finch/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/travis/miniconda/envs/finch/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/miniconda/envs/finch/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/travis/miniconda/envs/finch/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/travis/miniconda/envs/finch/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/travis/miniconda/envs/finch/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/miniconda/envs/finch/lib/python3.7/site-packages/nbval/plugin.py", line 115, in pytest_collect_file
    return IPyNbFile(path, parent)
  File "/home/travis/miniconda/envs/finch/lib/python3.7/site-packages/_pytest/nodes.py", line 95, in __call__
    warnings.warn(NODE_USE_FROM_PARENT.format(name=self.__name__), stacklevel=2)
pytest.PytestDeprecationWarning: Direct construction of IPyNbFile has been deprecated, please use IPyNbFile.from_parent.
See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.
=========================== short test summary info ============================
ERROR  - pytest.PytestDeprecationWarning: Direct construction of IPyNbFile ha...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
[31m=============================== [31m[1m1 error[0m[31m in 0.13s[0m[31m ===============================[0m
Makefile:128: recipe for target 'test-notebooks' failed
make: *** [test-notebooks] Error 2
```

**Comment by Zeitsperre** [comment]
I'm going to try running/building this locally and see if there's any clear explanation as to why this is failing now.

**Comment by tlvu** [comment]
> I'm going to try running/building this locally and see if there's any clear explanation as to why this is failing now.

Same here, trying to reproduce locally and also retrigger the same Travis build in case it's a fluke on Travis side.

**Comment by Zeitsperre** [comment]
Looks like it's due to a deprecated call in `pytest` that the notebook-based plugins haven't adapted for yet. No issues when downgrading `pytest` below 6.0.0.

**Comment by tlvu** [comment]
Yes, looks like we have to pin older pytest version for the moment: https://github.com/computationalmodelling/nbval/issues/139

**Comment by tlvu** [comment]
> Yes, looks like we have to pin older pytest version for the moment: [computationalmodelling/nbval#139](https://github.com/computationalmodelling/nbval/issues/139)

pytest 6.0.0 has been released yesterday July 28 !  Just in-time to break my PR :(

**Comment by Zeitsperre** [comment]
> pytest 6.0.0 has been released yesterday July 28 ! Just in-time to break my PR :(

The best time to release a breaking version! I imagine you'll be making changes in the upstream cookiecutter?

**Comment by tlvu** [comment]
> The best time to release a breaking version! I imagine you'll be making changes in the upstream cookiecutter?

Yup, already on it.

**Pull request merged**
