### PR TITLE
Update xclim

### PR DESCRIPTION
**Pull request by Zeitsperre**
## Overview

Changes:

* `finch` is now compatible with the latest `xclim` (v0.53.2) and `xscen` (v0.10.1).
* Python 3.12 is now supported; Python 3.10+ coding conventions are now standard.
* Python 3.8 and 3.9 support has been dropped.
* The tempfile management for testing has been significantly improved.

## Additional Information

Once this PR is merged and the cookiecutter is updated, we should be able to tag a new version.

### CODE REVIEW

**Comment by aulemahal** [comment]
@tlogan2000 Indeed, there was a dict-like access on a `Parameter` object, which lost that feature in recent xclim. However, there is also a bug in xclim.

The indicator "frost_free_spell_max_length" has the default ">=" for its parameter `op`. But in its docstring, it lists the possible choices for `op` as `<, <=, le, lt`... A faulty copy-paste I presume. I added a workaround that spits a log error.

**Comment by aulemahal** [comment]
Yish. I'll leave you the stats / discharge issues, but `cf-xarray`'s `reshape_unique_geometries` seems completely broken with the newest xarray...

**Comment by tlogan2000** [comment]
@Zeitsperre @aulemahal I am starting to implement changes to the spatial averaging section of the ensembles code (using xscen but with this branch as a starting point).  Opinions whether I should push these "xscen" changes in this branch directly?

**Comment by Zeitsperre** [comment]
@tlogan2000 I would make a branch based off of this work. We don't want to mix up the conversion work with the new features if we can. It's bad enough haha

**Review by tlogan2000 — APPROVED** [review]

**Comment by Zeitsperre** [comment]
FYI, we're seeing some funny errors on the docker image:
```
 ERROR:PYWPS:Indicator frost_free_spell_max_length has incorrect choices for parameter op : default >= not in ['<', '<=', 'lt', 'le']
/opt/conda/envs/finch/lib/python3.12/site-packages/xclim/core/locales.py:189: UserWarning: Attributes of indicator HXMAX_DAYS_ABOVE in language fr were requested, but none were found.
/opt/conda/envs/finch/lib/python3.12/site-packages/xclim/core/locales.py:189: UserWarning: Attributes of indicator DISCHARGE_STATS in language fr were requested, but none were found.
/opt/conda/envs/finch/lib/python3.12/site-packages/xclim/core/locales.py:189: UserWarning: Attributes of indicator FREQ_ANALYSIS in language fr were requested, but none were found.
/opt/conda/envs/finch/lib/python3.12/site-packages/xclim/core/locales.py:189: UserWarning: Attributes of indicator DISCHARGE_DISTRIBUTION_FIT in language fr were requested, but none were found.
ERROR:PYWPS:Indicator frost_free_spell_max_length has incorrect choices for parameter op : default >= not in ['<', '<=', 'lt', 'le']
ERROR:PYWPS:Indicator frost_free_spell_max_length has incorrect choices for parameter op : default >= not in ['<', '<=', 'lt', 'le']
ERROR:PYWPS:Indicator frost_free_spell_max_length has incorrect choices for parameter op : default >= not in ['<', '<=', 'lt', 'le']
INFO:PYWPS:Configuration file(s) ['/opt/conda/envs/finch/lib/python3.12/site-packages/finch/default.cfg'] loaded
/opt/conda/envs/finch/lib/python3.12/site-packages/xclim/core/indicator.py:255: UserWarning: Class humidex.HXMAX_DAYS_ABOVE already exists and will be overwritten.
/opt/conda/envs/finch/lib/python3.12/site-packages/xclim/core/indicator.py:255: UserWarning: Class streamflow.DISCHARGE_STATS already exists and will be overwritten.
/opt/conda/envs/finch/lib/python3.12/site-packages/xclim/core/indicator.py:255: UserWarning: Class streamflow.FREQ_ANALYSIS already exists and will be overwritten.
/opt/conda/envs/finch/lib/python3.12/site-packages/xclim/core/indicator.py:255: UserWarning: Class streamflow.DISCHARGE_DISTRIBUTION_FIT already exists and will be overwritten.
ERROR:PYWPS:Indicator frost_free_spell_max_length has incorrect choices for parameter op : default >= not in ['<', '<=', 'lt', 'le']
ERROR:PYWPS:Indicator frost_free_spell_max_length has incorrect choices for parameter op : default >= not in ['<', '<=', 'lt', 'le']
ERROR:PYWPS:Indicator frost_free_spell_max_length has incorrect choices for parameter op : default >= not in ['<', '<=', 'lt', 'le']
ERROR:PYWPS:Indicator frost_free_spell_max_length has incorrect choices for parameter op : default >= not in ['<', '<=', 'lt', 'le']
forked process id: 16
starting WPS service on http://localhost:5000/wps
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:5000
```
Might want to verify firs that there are things we should set in `finch` before opening issues in `xclim`.

**Comment by aulemahal** [comment]
The "ERROR" lines should be fixed in the latest xclim. The attributes issue I don't know, but who cares. The reloading warnings are ok to ignore.

**Pull request merged**
