### PR TITLE
[WIP] implement `before_date` and `mid_date` inputs

### LINKED ISSUE #106: Implement MM-DD date of the year inputs
## Description

Some indicators are skipped: 
 - growing_season_length
 - growing_season_end
 - last_spring_frost

because their `mid_date` or `before_date` 'date of the year' inputs are not implemented

### PR DESCRIPTION
**Pull request by davidcaron**
## Overview

This PR fixes #106

### CODE REVIEW

**Comment by davidcaron** [comment]
I'm having problems with the 3 new indicators: `growing_season_end`, `growing_season_length` and `last_spring_frost` maybe @Zeitsperre you could help figure it out?

The test case that breaks is `tests/test_wps_xclim_indices.py::test_processes`

For each process, I will copy their error tracebacks:

`growing_season_end` and `growing_season_length` (same error): 
```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/pywps/app/Process.py", line 243, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/c/projects/finch/finch/processes/wps_base.py", line 35, in _handler_wrapper
    return self.wrapped_handler(request, response)
  File "/c/projects/finch/finch/processes/wps_xclim_indices.py", line 105, in _handler
    out = compute_indices(self, self.xci, inputs)
  File "/c/projects/finch/finch/processes/utils.py", line 135, in compute_indices 
    out = func(**kwds)
  File "/c/projects/xclim/xclim/core/indicator.py", line 193, in __call__
    out = self.compute(*das, **ba.kwargs)
  File "/c/projects/xclim/xclim/core/units.py", line 354, in wrapper
    out = func(*args, **kwargs)
  File "/c/projects/xclim/xclim/indices/_threshold.py", line 387, in growing_season_end
    return cond.resample(time=freq).map(
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/xarray/core/resample.py", line 222, in map
    combined = super().map(func, shortcut=shortcut, args=args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/xarray/core/groupby.py", line 806, in map
    return self._combine(applied, shortcut=shortcut)
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/xarray/core/groupby.py", line 830, in _combine
    combined = concat(applied, dim)
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/xarray/core/concat.py", line 135, in concat
    return f(objs, dim, data_vars, coords, compat, positions, fill_value, join)
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/xarray/core/concat.py", line 431, in _dataarray_concat   
    ds = _dataset_concat(
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/xarray/core/concat.py", line 324, in _dataset_concat     
    concat_over, equals, concat_dim_lengths = _calc_concat_over(
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/xarray/core/concat.py", line 258, in _calc_concat_over   
    process_subset_opt(coords, "coords")
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/xarray/core/concat.py", line 197, in process_subset_opt  
    variables = [ds.variables[k] for ds in datasets]
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/xarray/core/concat.py", line 197, in <listcomp>
    variables = [ds.variables[k] for ds in datasets]
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/xarray/core/utils.py", line 386, in __getitem__
    return self.mapping[key]
KeyError: 'time'
```

`growing_season_length`: 
```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/pywps/app/Process.py", line 243, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/c/projects/finch/finch/processes/wps_base.py", line 35, in _handler_wrapper
    return self.wrapped_handler(request, response)
  File "/c/projects/finch/finch/processes/wps_xclim_indices.py", line 105, in _handler
    out = compute_indices(self, self.xci, inputs) 
  File "/c/projects/finch/finch/processes/utils.py", line 135, in compute_indices
    out = func(**kwds)
  File "/c/projects/xclim/xclim/core/indicator.py", line 196, in __call__
    out = convert_units_to(out, self.units, self.context)
  File "/c/projects/xclim/xclim/core/units.py", line 254, in convert_units_to
    data=units.convert(source.values, fu, tu),
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/pint/registry.py", line 925, in convert
    return self._convert(value, src, dst, inplace) 
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/pint/registry.py", line 1762, in _convert
    return super()._convert(value, src, dst, inplace)
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/pint/registry.py", line 1376, in _convert
    return super()._convert(value, src, dst, inplace)
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.8/site-packages/pint/registry.py", line 958, in _convert
    raise DimensionalityError(src, dst, src_dim, dst_dim)
pint.errors.DimensionalityError: Cannot convert from 'day' ([time]) to 'dimensionless' (dimensionless)
```


`last_spring_frost`: 
```

```

**Comment by Zeitsperre** [comment]
Tagging @aulemahal on this as he might have more of an understanding. I might need to push a hotfix release to deal with this once we figure out why this is happening.

**Comment by aulemahal** [comment]
Vite de même, the error with `last_spring_frost` is from xclim : the indice and the indicator define different, incompatible, units. @Zeitsperre simply editing the Indicator declaration in atmos with "units='days'" should solve it.
The first errors seems to come from xarray's resampling? I'll be back for more.

**Comment by aulemahal** [comment]
Ouf... The issue is with "mid_date" falling outside of some resampling periods. When "mid_date" is not in the period, the run_length util returns an array full of NaN that still has a singleton "time" dimension, but the real output (when "mid_date" does exist) doesn't have a "time". So xarray's resample is confused at this mixed output and fails. @Zeitsperre I can write a fix for that.

**Comment by huard** [comment]
The other indicators whose output is a day of the year have no units.

**Comment by davidcaron** [comment]
@aulemahal any updates on this?
Adding @matprov to the conversation

**Comment by aulemahal** [comment]
Sorry, I forgot about that! I believe Ouranosinc/xclim#408 fixes the issues!

**Comment by Zeitsperre** [comment]
@davidcaron With xclim 0.15.2, you should be able to continue on this PR.

**Pull request merged**
