### PR TITLE
Adjust csv

### LINKED ISSUE #303: Reorder csv output columns
## Description

CSV exports can occasionnally not have coords (time, lat, lon) as first 3 columns

most likely only here where data is concatenated together 
https://github.com/bird-house/finch/blob/1b137c8c766a646d5c31d1b003415d731fbc9e3d/finch/processes/utils.py#L626C15-L626C15

but possibly here as well
https://github.com/bird-house/finch/blob/1b137c8c766a646d5c31d1b003415d731fbc9e3d/finch/processes/utils.py#L638

### PR DESCRIPTION
**Pull request by tlogan2000**
## Overview

This PR fixes #303 

Changes:

* Adjust dataframe columns before export

Links to other issues or sources.

### CODE REVIEW

**Comment by aulemahal** [comment]
Errors in the CI here and in #302 should be fixed by pangeo-data/xESMF#308.

**Comment by tlogan2000** [comment]
> Errors in the CI here and in #302 should be fixed by [pangeo-data/xESMF#308](https://github.com/pangeo-data/xESMF/pull/308).

Ok thx. Any ETA on PR merge / new xESMF release?    I assume pinning xESMF to 0.7.x would make finch work as before?

**Comment by aulemahal** [comment]
I guess we'll release a new xESMF quickly as this bug breaks the normal usage. I'll try to have the fix completed today.

**Comment by tlogan2000** [comment]
@aulemahal can you give a final approval?

**Review by aulemahal — APPROVED** [review]

**Pull request merged**
