### PR TITLE
Use xscen new

### PR DESCRIPTION
**Pull request by tlogan2000**
## Overview

This PR fixes [issue id]

Changes:

* Added ...

## Additional Information

Links to other issues or sources.

### CODE REVIEW

**Comment by tlogan2000** [comment]
Local run of test suite are struggling triggering pull request to see test failures.

**Comment by tlogan2000** [comment]
@aulemahal  @Zeitsperre  ... any idea why I get a permission error for `test_wps_ensemble.py::test_ensemble_hxmax_days_above_grid_point`  ??

**Comment by aulemahal** [comment]
I really can't see why... All the other tests pass and they do the same thing...

**Comment by aulemahal** [comment]
@tlogan2000 Hypothèse : the issue stems from temporary directories. I switched most (all?) temp file handling in the tests to use pytest's functions instead of custom ones. 

The notebook error were coming from a faulty `is_opendap_url` function. The function was performing a test that worked with Thredds v4, but does not with v5. From what I understand of the OpenDAP doc, the previous test was not *required* to work, but  my change should. 

In details : we were making a HEAD request on the "raw" URL. OpenDAP does not specify what the server should return when hitting the pure dataset url without any query. Thredds v4 was returning something, v5 is returning an error. My solution is to request the "metadata" of the dataset using the ".dds" "query", which is something all OpenDAP server should be able to do.

**Comment by aulemahal** [comment]
Changing the temp dir methods didn't work, but dropping python 3.9 did. 

Any reasons not to,  @Zeitsperre ? I think finch is solely used by ClimateData and through it's docker image which installs python 3.12 by default I think.

**Comment by Zeitsperre** [comment]
@aulemahal Dropping Python3.9 is fine. We've already done this in recent versions of `xclim` and `xscen`. This is a web service, so an especially wide range of compatible Python versions isn't as important.

**Review by Zeitsperre — APPROVED** [review]
LGTM

I think I might update the cookiecutter once this is merged in, then we can release a new version. Great work!

**Review by aulemahal — APPROVED** [review]

**Comment by Zeitsperre** [comment]
This is just waiting on an update to the changelog. Thanks again!

**Pull request merged**
